#:schema https://json.schemastore.org/any.json
[build]
  cmd = "go build -o main main.go"
  # Binary to watch
  bin = "main"
  dir = "."
  include_ext = ["go"]
  exclude_dir = ["vendor"]
  run_after_build = "chmod +x main"
[log]
  level = "debug"
