apiVersion: v1
kind: Service
metadata:
  name: express-app-svc
  labels:
    app: express-app
spec:
  type: LoadBalancer
  selector:
    app: express-app
  ports:
    - port: 80           
      targetPort: 3000   
      protocol: TCP
