apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base

nameSuffix: -stage 
namePrefix: app-1-

labels:
  - pairs:
      env: stage
    includeSelectors: true

images:
- name: nginx
  newName: nginx
  newTag: "1.24"
commonAnnotations:
      branch: stage
      support: 800-800
namespace: stage
replicas:
  - name: nginx-deployment
    count: 4
